package com.springboot2.business.sample.service;

import com.springboot2.business.sample.dataset.TUser;
import com.springboot2.business.sample.dataset.TUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    long countByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    int deleteByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    int insertSelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    List<TUser> selectByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    TUser selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") TUser record, @Param("example") TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    int updateByExample(@Param("record") TUser record, @Param("example") TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    int updateByPrimaryKeySelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbg.generated Tue Dec 26 05:15:32 CST 2017
     */
    int updateByPrimaryKey(TUser record);
}